2025-08-26 15:45:38 [ERROR]: Update user error: Cast to ObjectId failed for value "profile" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "profile" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"profile\"",
  "kind": "ObjectId",
  "value": "profile",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-26 15:45:57 [ERROR]: Update user error: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"preferences\"",
  "kind": "ObjectId",
  "value": "preferences",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-26 15:46:16 [ERROR]: Update user error: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"preferences\"",
  "kind": "ObjectId",
  "value": "preferences",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-26 15:46:24 [ERROR]: Update user error: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"preferences\"",
  "kind": "ObjectId",
  "value": "preferences",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-26 15:52:40 [ERROR]: Error sending verification email: sendEmail is not a function
TypeError: sendEmail is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:84:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 15:58:26 [ERROR]: Update user error: Cast to ObjectId failed for value "profile" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "profile" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"profile\"",
  "kind": "ObjectId",
  "value": "profile",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-26 16:47:14 [ERROR]: Login error: option expires is invalid
TypeError: option expires is invalid
    at Object.serialize (C:\Users\Admin\Documents\new\server\node_modules\cookie\index.js:234:13)
    at res.cookie (C:\Users\Admin\Documents\new\server\node_modules\express\lib\response.js:892:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:200:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 16:47:31 [ERROR]: Login error: option expires is invalid
TypeError: option expires is invalid
    at Object.serialize (C:\Users\Admin\Documents\new\server\node_modules\cookie\index.js:234:13)
    at res.cookie (C:\Users\Admin\Documents\new\server\node_modules\express\lib\response.js:892:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:200:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 16:49:41 [ERROR]: Login error: option expires is invalid
TypeError: option expires is invalid
    at Object.serialize (C:\Users\Admin\Documents\new\server\node_modules\cookie\index.js:234:13)
    at res.cookie (C:\Users\Admin\Documents\new\server\node_modules\express\lib\response.js:892:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:200:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 16:51:33 [ERROR]: Login error: option expires is invalid
TypeError: option expires is invalid
    at Object.serialize (C:\Users\Admin\Documents\new\server\node_modules\cookie\index.js:234:13)
    at res.cookie (C:\Users\Admin\Documents\new\server\node_modules\express\lib\response.js:892:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:200:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 16:51:55 [ERROR]: Login error: option expires is invalid
TypeError: option expires is invalid
    at Object.serialize (C:\Users\Admin\Documents\new\server\node_modules\cookie\index.js:234:13)
    at res.cookie (C:\Users\Admin\Documents\new\server\node_modules\express\lib\response.js:892:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:200:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 16:53:26 [ERROR]: Login error: option expires is invalid
TypeError: option expires is invalid
    at Object.serialize (C:\Users\Admin\Documents\new\server\node_modules\cookie\index.js:234:13)
    at res.cookie (C:\Users\Admin\Documents\new\server\node_modules\express\lib\response.js:892:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:200:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-26 20:09:51 [ERROR]: Error sending verification email: sendEmail is not a function
TypeError: sendEmail is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:84:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-28 11:27:24 [ERROR]: Database connection failed: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017
    at _handleConnectionErrors (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\connection.js:1165:11)
    at NativeConnection.openUri (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\connection.js:1096:11)
    at async connectDB (C:\Users\Admin\Documents\new\server\config\database.js:6:18)
{
  "errorLabelSet": {},
  "reason": {
    "type": "Unknown",
    "servers": {
      "localhost:27017": {
        "address": "localhost:27017",
        "type": "Unknown",
        "hosts": [],
        "passives": [],
        "arbiters": [],
        "tags": {},
        "minWireVersion": 0,
        "maxWireVersion": 0,
        "roundTripTime": -1,
        "minRoundTripTime": 0,
        "lastUpdateTime": 50914654,
        "lastWriteDate": 0,
        "error": {
          "errorLabelSet": {},
          "beforeHandshake": false
        },
        "topologyVersion": null,
        "setName": null,
        "setVersion": null,
        "electionId": null,
        "logicalSessionTimeoutMinutes": null,
        "maxMessageSizeBytes": null,
        "maxWriteBatchSize": null,
        "maxBsonObjectSize": null,
        "primary": null,
        "me": null,
        "$clusterTime": null,
        "iscryptd": false
      }
    },
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": null,
    "maxElectionId": null,
    "maxSetVersion": null,
    "commonWireVersion": 0,
    "logicalSessionTimeoutMinutes": null
  },
  "cause": {
    "type": "Unknown",
    "servers": {
      "localhost:27017": {
        "address": "localhost:27017",
        "type": "Unknown",
        "hosts": [],
        "passives": [],
        "arbiters": [],
        "tags": {},
        "minWireVersion": 0,
        "maxWireVersion": 0,
        "roundTripTime": -1,
        "minRoundTripTime": 0,
        "lastUpdateTime": 50914654,
        "lastWriteDate": 0,
        "error": {
          "errorLabelSet": {},
          "beforeHandshake": false
        },
        "topologyVersion": null,
        "setName": null,
        "setVersion": null,
        "electionId": null,
        "logicalSessionTimeoutMinutes": null,
        "maxMessageSizeBytes": null,
        "maxWriteBatchSize": null,
        "maxBsonObjectSize": null,
        "primary": null,
        "me": null,
        "$clusterTime": null,
        "iscryptd": false
      }
    },
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": null,
    "maxElectionId": null,
    "maxSetVersion": null,
    "commonWireVersion": 0,
    "logicalSessionTimeoutMinutes": null
  }
}
2025-08-28 11:28:20 [ERROR]: Database connection failed: Authentication failed.
MongoServerError: Authentication failed.
    at Connection.sendCommand (C:\Users\Admin\Documents\new\server\node_modules\mongodb\lib\cmap\connection.js:305:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Connection.command (C:\Users\Admin\Documents\new\server\node_modules\mongodb\lib\cmap\connection.js:333:26)
    at async continueScramConversation (C:\Users\Admin\Documents\new\server\node_modules\mongodb\lib\cmap\auth\scram.js:131:15)
    at async ScramSHA256.auth (C:\Users\Admin\Documents\new\server\node_modules\mongodb\lib\cmap\auth\scram.js:37:20)
    at async performInitialHandshake (C:\Users\Admin\Documents\new\server\node_modules\mongodb\lib\cmap\connect.js:104:13)
    at async connect (C:\Users\Admin\Documents\new\server\node_modules\mongodb\lib\cmap\connect.js:24:9)
{
  "errorLabelSet": {},
  "errorResponse": {
    "ok": 0,
    "errmsg": "Authentication failed.",
    "code": 18,
    "codeName": "AuthenticationFailed"
  },
  "ok": 0,
  "code": 18,
  "codeName": "AuthenticationFailed",
  "connectionGeneration": 0
}
2025-08-28 11:30:24 [ERROR]: Database connection failed: getaddrinfo ENOTFOUND 123
MongooseServerSelectionError: getaddrinfo ENOTFOUND 123
    at _handleConnectionErrors (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\connection.js:1165:11)
    at NativeConnection.openUri (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\connection.js:1096:11)
    at async connectDB (C:\Users\Admin\Documents\new\server\config\database.js:6:18)
{
  "errorLabelSet": {},
  "reason": {
    "type": "Unknown",
    "servers": {
      "123:27017": {
        "address": "123:27017",
        "type": "Unknown",
        "hosts": [],
        "passives": [],
        "arbiters": [],
        "tags": {},
        "minWireVersion": 0,
        "maxWireVersion": 0,
        "roundTripTime": -1,
        "minRoundTripTime": 0,
        "lastUpdateTime": 51094375,
        "lastWriteDate": 0,
        "error": {
          "errorLabelSet": {},
          "beforeHandshake": false
        },
        "topologyVersion": null,
        "setName": null,
        "setVersion": null,
        "electionId": null,
        "logicalSessionTimeoutMinutes": null,
        "maxMessageSizeBytes": null,
        "maxWriteBatchSize": null,
        "maxBsonObjectSize": null,
        "primary": null,
        "me": null,
        "$clusterTime": null,
        "iscryptd": false
      }
    },
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": null,
    "maxElectionId": null,
    "maxSetVersion": null,
    "commonWireVersion": 0,
    "logicalSessionTimeoutMinutes": null
  },
  "cause": {
    "type": "Unknown",
    "servers": {
      "123:27017": {
        "address": "123:27017",
        "type": "Unknown",
        "hosts": [],
        "passives": [],
        "arbiters": [],
        "tags": {},
        "minWireVersion": 0,
        "maxWireVersion": 0,
        "roundTripTime": -1,
        "minRoundTripTime": 0,
        "lastUpdateTime": 51094375,
        "lastWriteDate": 0,
        "error": {
          "errorLabelSet": {},
          "beforeHandshake": false
        },
        "topologyVersion": null,
        "setName": null,
        "setVersion": null,
        "electionId": null,
        "logicalSessionTimeoutMinutes": null,
        "maxMessageSizeBytes": null,
        "maxWriteBatchSize": null,
        "maxBsonObjectSize": null,
        "primary": null,
        "me": null,
        "$clusterTime": null,
        "iscryptd": false
      }
    },
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": null,
    "maxElectionId": null,
    "maxSetVersion": null,
    "commonWireVersion": 0,
    "logicalSessionTimeoutMinutes": null
  }
}
2025-08-28 11:49:37 [ERROR]: Database connection failed: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017
    at _handleConnectionErrors (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\connection.js:1165:11)
    at NativeConnection.openUri (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\connection.js:1096:11)
    at async connectDB (C:\Users\Admin\Documents\new\server\config\database.js:6:18)
{
  "errorLabelSet": {},
  "reason": {
    "type": "Unknown",
    "servers": {
      "localhost:27017": {
        "address": "localhost:27017",
        "type": "Unknown",
        "hosts": [],
        "passives": [],
        "arbiters": [],
        "tags": {},
        "minWireVersion": 0,
        "maxWireVersion": 0,
        "roundTripTime": -1,
        "minRoundTripTime": 0,
        "lastUpdateTime": 813161,
        "lastWriteDate": 0,
        "error": {
          "errorLabelSet": {},
          "beforeHandshake": false
        },
        "topologyVersion": null,
        "setName": null,
        "setVersion": null,
        "electionId": null,
        "logicalSessionTimeoutMinutes": null,
        "maxMessageSizeBytes": null,
        "maxWriteBatchSize": null,
        "maxBsonObjectSize": null,
        "primary": null,
        "me": null,
        "$clusterTime": null,
        "iscryptd": false
      }
    },
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": null,
    "maxElectionId": null,
    "maxSetVersion": null,
    "commonWireVersion": 0,
    "logicalSessionTimeoutMinutes": null
  },
  "cause": {
    "type": "Unknown",
    "servers": {
      "localhost:27017": {
        "address": "localhost:27017",
        "type": "Unknown",
        "hosts": [],
        "passives": [],
        "arbiters": [],
        "tags": {},
        "minWireVersion": 0,
        "maxWireVersion": 0,
        "roundTripTime": -1,
        "minRoundTripTime": 0,
        "lastUpdateTime": 813161,
        "lastWriteDate": 0,
        "error": {
          "errorLabelSet": {},
          "beforeHandshake": false
        },
        "topologyVersion": null,
        "setName": null,
        "setVersion": null,
        "electionId": null,
        "logicalSessionTimeoutMinutes": null,
        "maxMessageSizeBytes": null,
        "maxWriteBatchSize": null,
        "maxBsonObjectSize": null,
        "primary": null,
        "me": null,
        "$clusterTime": null,
        "iscryptd": false
      }
    },
    "stale": false,
    "compatible": true,
    "heartbeatFrequencyMS": 10000,
    "localThresholdMS": 15,
    "setName": null,
    "maxElectionId": null,
    "maxSetVersion": null,
    "commonWireVersion": 0,
    "logicalSessionTimeoutMinutes": null
  }
}
2025-08-28 11:58:14 [ERROR]: Update user error: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"preferences\"",
  "kind": "ObjectId",
  "value": "preferences",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-28 11:59:07 [ERROR]: Update user error: Cast to ObjectId failed for value "change-password" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "change-password" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"change-password\"",
  "kind": "ObjectId",
  "value": "change-password",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-29 00:26:05 [ERROR]: Email sending error:
{
  "error": "nodemailer.createTransporter is not a function",
  "recipient": "johnsonemmanuel1425@gmail.com",
  "subject": "Password Reset Request - Hospital Management System"
}
2025-08-29 00:26:05 [ERROR]: Error sending password reset email: nodemailer.createTransporter is not a function
TypeError: nodemailer.createTransporter is not a function
    at sendEmail (C:\Users\Admin\Documents\new\server\utils\sendEmail.js:7:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:333:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-29 00:26:49 [ERROR]: Email sending error:
{
  "error": "nodemailer.createTransporter is not a function",
  "recipient": "johnson1425@hospital.com",
  "subject": "Password Reset Request - Hospital Management System"
}
2025-08-29 00:26:49 [ERROR]: Error sending password reset email: nodemailer.createTransporter is not a function
TypeError: nodemailer.createTransporter is not a function
    at sendEmail (C:\Users\Admin\Documents\new\server\utils\sendEmail.js:7:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:333:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-29 00:48:01 [ERROR]: Update user error: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
CastError: Cast to ObjectId failed for value "preferences" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\users.js:114:16
{
  "stringValue": "\"preferences\"",
  "kind": "ObjectId",
  "value": "preferences",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-29 00:48:32 [ERROR]: Email sending error:
{
  "error": "nodemailer.createTransporter is not a function",
  "recipient": "johnson1425@hospital.com",
  "subject": "Password Reset Request - Hospital Management System"
}
2025-08-29 00:48:32 [ERROR]: Error sending password reset email: nodemailer.createTransporter is not a function
TypeError: nodemailer.createTransporter is not a function
    at sendEmail (C:\Users\Admin\Documents\new\server\utils\sendEmail.js:7:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:333:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 18:29:58 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 18:32:20 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 18:35:23 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 18:35:38 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 18:40:29 [ERROR]: Error setting up admin user: User validation failed: gender: `other` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
ValidationError: User validation failed: gender: `other` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`other` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`other` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "other",
        "length": 5
      },
      "kind": "enum",
      "path": "gender",
      "value": "other"
    },
    "permissions.12": {
      "name": "ValidatorError",
      "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
      "properties": {
        "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.12",
        "value": "read:dashboard",
        "length": 14
      },
      "kind": "enum",
      "path": "permissions.12",
      "value": "read:dashboard"
    },
    "permissions.13": {
      "name": "ValidatorError",
      "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
      "properties": {
        "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.13",
        "value": "write:dashboard",
        "length": 15
      },
      "kind": "enum",
      "path": "permissions.13",
      "value": "write:dashboard"
    },
    "permissions.21": {
      "name": "ValidatorError",
      "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
      "properties": {
        "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.21",
        "value": "start:visits",
        "length": 12
      },
      "kind": "enum",
      "path": "permissions.21",
      "value": "start:visits"
    },
    "permissions.22": {
      "name": "ValidatorError",
      "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
      "properties": {
        "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.22",
        "value": "end:visits",
        "length": 10
      },
      "kind": "enum",
      "path": "permissions.22",
      "value": "end:visits"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 18:41:52 [ERROR]: Error setting up admin user: User validation failed: gender: `other` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
ValidationError: User validation failed: gender: `other` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`other` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`other` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "other",
        "length": 5
      },
      "kind": "enum",
      "path": "gender",
      "value": "other"
    },
    "permissions.12": {
      "name": "ValidatorError",
      "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
      "properties": {
        "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.12",
        "value": "read:dashboard",
        "length": 14
      },
      "kind": "enum",
      "path": "permissions.12",
      "value": "read:dashboard"
    },
    "permissions.13": {
      "name": "ValidatorError",
      "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
      "properties": {
        "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.13",
        "value": "write:dashboard",
        "length": 15
      },
      "kind": "enum",
      "path": "permissions.13",
      "value": "write:dashboard"
    },
    "permissions.21": {
      "name": "ValidatorError",
      "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
      "properties": {
        "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.21",
        "value": "start:visits",
        "length": 12
      },
      "kind": "enum",
      "path": "permissions.21",
      "value": "start:visits"
    },
    "permissions.22": {
      "name": "ValidatorError",
      "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
      "properties": {
        "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.22",
        "value": "end:visits",
        "length": 10
      },
      "kind": "enum",
      "path": "permissions.22",
      "value": "end:visits"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 18:44:27 [ERROR]: Error setting up admin user: User validation failed: gender: `other` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
ValidationError: User validation failed: gender: `other` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`other` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`other` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "other",
        "length": 5
      },
      "kind": "enum",
      "path": "gender",
      "value": "other"
    },
    "permissions.12": {
      "name": "ValidatorError",
      "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
      "properties": {
        "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.12",
        "value": "read:dashboard",
        "length": 14
      },
      "kind": "enum",
      "path": "permissions.12",
      "value": "read:dashboard"
    },
    "permissions.13": {
      "name": "ValidatorError",
      "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
      "properties": {
        "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.13",
        "value": "write:dashboard",
        "length": 15
      },
      "kind": "enum",
      "path": "permissions.13",
      "value": "write:dashboard"
    },
    "permissions.21": {
      "name": "ValidatorError",
      "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
      "properties": {
        "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.21",
        "value": "start:visits",
        "length": 12
      },
      "kind": "enum",
      "path": "permissions.21",
      "value": "start:visits"
    },
    "permissions.22": {
      "name": "ValidatorError",
      "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
      "properties": {
        "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.22",
        "value": "end:visits",
        "length": 10
      },
      "kind": "enum",
      "path": "permissions.22",
      "value": "end:visits"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 18:46:26 [ERROR]: Error setting up admin user: User validation failed: gender: `male` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
ValidationError: User validation failed: gender: `male` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    },
    "permissions.12": {
      "name": "ValidatorError",
      "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
      "properties": {
        "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.12",
        "value": "read:dashboard",
        "length": 14
      },
      "kind": "enum",
      "path": "permissions.12",
      "value": "read:dashboard"
    },
    "permissions.13": {
      "name": "ValidatorError",
      "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
      "properties": {
        "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.13",
        "value": "write:dashboard",
        "length": 15
      },
      "kind": "enum",
      "path": "permissions.13",
      "value": "write:dashboard"
    },
    "permissions.21": {
      "name": "ValidatorError",
      "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
      "properties": {
        "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.21",
        "value": "start:visits",
        "length": 12
      },
      "kind": "enum",
      "path": "permissions.21",
      "value": "start:visits"
    },
    "permissions.22": {
      "name": "ValidatorError",
      "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
      "properties": {
        "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.22",
        "value": "end:visits",
        "length": 10
      },
      "kind": "enum",
      "path": "permissions.22",
      "value": "end:visits"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 18:48:18 [ERROR]: Error setting up admin user: User validation failed: gender: `male` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
ValidationError: User validation failed: gender: `male` is not a valid enum value for path `gender`., permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    },
    "permissions.12": {
      "name": "ValidatorError",
      "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
      "properties": {
        "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.12",
        "value": "read:dashboard",
        "length": 14
      },
      "kind": "enum",
      "path": "permissions.12",
      "value": "read:dashboard"
    },
    "permissions.13": {
      "name": "ValidatorError",
      "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
      "properties": {
        "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.13",
        "value": "write:dashboard",
        "length": 15
      },
      "kind": "enum",
      "path": "permissions.13",
      "value": "write:dashboard"
    },
    "permissions.21": {
      "name": "ValidatorError",
      "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
      "properties": {
        "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.21",
        "value": "start:visits",
        "length": 12
      },
      "kind": "enum",
      "path": "permissions.21",
      "value": "start:visits"
    },
    "permissions.22": {
      "name": "ValidatorError",
      "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
      "properties": {
        "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.22",
        "value": "end:visits",
        "length": 10
      },
      "kind": "enum",
      "path": "permissions.22",
      "value": "end:visits"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 18:49:23 [ERROR]: Error setting up admin user: User validation failed: gender: `male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 18:53:45 [ERROR]: Error setting up admin user: User validation failed: permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
ValidationError: User validation failed: permissions.12: `read:dashboard` is not a valid enum value for path `permissions.12`., permissions.13: `write:dashboard` is not a valid enum value for path `permissions.13`., permissions.21: `start:visits` is not a valid enum value for path `permissions.21`., permissions.22: `end:visits` is not a valid enum value for path `permissions.22`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "permissions.12": {
      "name": "ValidatorError",
      "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
      "properties": {
        "message": "`read:dashboard` is not a valid enum value for path `permissions.12`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.12",
        "value": "read:dashboard",
        "length": 14
      },
      "kind": "enum",
      "path": "permissions.12",
      "value": "read:dashboard"
    },
    "permissions.13": {
      "name": "ValidatorError",
      "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
      "properties": {
        "message": "`write:dashboard` is not a valid enum value for path `permissions.13`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.13",
        "value": "write:dashboard",
        "length": 15
      },
      "kind": "enum",
      "path": "permissions.13",
      "value": "write:dashboard"
    },
    "permissions.21": {
      "name": "ValidatorError",
      "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
      "properties": {
        "message": "`start:visits` is not a valid enum value for path `permissions.21`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.21",
        "value": "start:visits",
        "length": 12
      },
      "kind": "enum",
      "path": "permissions.21",
      "value": "start:visits"
    },
    "permissions.22": {
      "name": "ValidatorError",
      "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
      "properties": {
        "message": "`end:visits` is not a valid enum value for path `permissions.22`.",
        "type": "enum",
        "enumValues": [
          "read:patients",
          "write:patients",
          "delete:patients",
          "read:doctors",
          "write:doctors",
          "delete:doctors",
          "read:appointments",
          "write:appointments",
          "delete:appointments",
          "read:visits",
          "write:visits",
          "delete:visits",
          "read:users",
          "write:users",
          "delete:users",
          "read:reports",
          "write:reports",
          "read:settings",
          "write:settings",
          "admin:all"
        ],
        "path": "permissions.22",
        "value": "end:visits",
        "length": 10
      },
      "kind": "enum",
      "path": "permissions.22",
      "value": "end:visits"
    }
  },
  "_message": "User validation failed"
}
2025-08-30 19:06:08 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 19:07:00 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 19:07:35 [ERROR]: Login error: user.resetLoginAttempts is not a function
TypeError: user.resetLoginAttempts is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:185:16
2025-08-30 19:08:15 [ERROR]: Login error: user.resetLoginAttempts is not a function
TypeError: user.resetLoginAttempts is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:185:16
2025-08-30 19:11:47 [ERROR]: Token verification failed: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at protect (C:\Users\Admin\Documents\new\server\middleware\auth.js:49:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 19:11:47 [ERROR]: Token verification failed: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at protect (C:\Users\Admin\Documents\new\server\middleware\auth.js:49:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 19:15:00 [ERROR]: Login error: user.incLoginAttempts is not a function
TypeError: user.incLoginAttempts is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:176:18
2025-08-30 23:01:02 [ERROR]: Token verification failed: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at protect (C:\Users\Admin\Documents\new\server\middleware\auth.js:49:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 23:01:02 [ERROR]: Token verification failed: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at protect (C:\Users\Admin\Documents\new\server\middleware\auth.js:49:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 23:05:01 [ERROR]: Login error: user.isLocked is not a function
TypeError: user.isLocked is not a function
    at C:\Users\Admin\Documents\new\server\routes\auth.js:164:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-30 23:39:28 [ERROR]: Registration error: User validation failed: gender: `female` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `female` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`female` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`female` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "female",
        "length": 6
      },
      "kind": "enum",
      "path": "gender",
      "value": "female"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 00:38:20 [ERROR]: Create patient error: Patient validation failed: medicalHistory: Cast to embedded failed for value "Diabetes" (type string) at path "medicalHistory" because of "ObjectParameterError", allergies: Parameter "obj" to Document() must be an object, got "" (type string), patientId: Path `patientId` is required.
ValidationError: Patient validation failed: medicalHistory: Cast to embedded failed for value "Diabetes" (type string) at path "medicalHistory" because of "ObjectParameterError", allergies: Parameter "obj" to Document() must be an object, got "" (type string), patientId: Path `patientId` is required.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at model.$set (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:1480:12)
    at model.$set (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:1132:16)
    at model.Document (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:178:12)
    at model.Model (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:127:12)
    at new model (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4834:15)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:2775:20
    at Array.map (<anonymous>)
    at Function.create (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:2763:34)
    at C:\Users\Admin\Documents\new\server\routes\patients.js:124:35
{
  "errors": {
    "medicalHistory": {
      "stringValue": "\"Diabetes\"",
      "valueType": "string",
      "kind": "embedded",
      "value": "Diabetes",
      "path": "medicalHistory",
      "reason": {},
      "name": "CastError",
      "message": "Cast to embedded failed for value \"Diabetes\" (type string) at path \"medicalHistory\" because of \"ObjectParameterError\""
    },
    "allergies": {},
    "patientId": {
      "name": "ValidatorError",
      "message": "Path `patientId` is required.",
      "properties": {
        "message": "Path `patientId` is required.",
        "type": "required",
        "path": "patientId"
      },
      "kind": "required",
      "path": "patientId"
    }
  },
  "_message": "Patient validation failed"
}
2025-08-31 01:00:00 [ERROR]: Create patient error: Patient validation failed: allergies: Parameter "obj" to Document() must be an object, got "" (type string)
ValidationError: Patient validation failed: allergies: Parameter "obj" to Document() must be an object, got "" (type string)
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at SchemaDocumentArray.doValidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\documentArray.js:247:12)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3111:18
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "allergies": {}
  },
  "_message": "Patient validation failed"
}
2025-08-31 02:01:41 [ERROR]: Get appointments error: Cannot populate path `patient` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `patient` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\appointments.js:20:26
{
  "path": "patient"
}
2025-08-31 16:29:15 [ERROR]: Get patient error: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
CastError: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\patients.js:62:21
{
  "stringValue": "\"search\"",
  "kind": "ObjectId",
  "value": "search",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-31 16:29:18 [ERROR]: Get patient error: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
CastError: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\patients.js:62:21
{
  "stringValue": "\"search\"",
  "kind": "ObjectId",
  "value": "search",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-31 16:33:54 [ERROR]: Get patient error: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
CastError: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\patients.js:62:21
{
  "stringValue": "\"search\"",
  "kind": "ObjectId",
  "value": "search",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-31 16:33:54 [ERROR]: Get patient error: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
CastError: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\patients.js:62:21
{
  "stringValue": "\"search\"",
  "kind": "ObjectId",
  "value": "search",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-31 16:36:55 [ERROR]: Get patient error: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
CastError: Cast to ObjectId failed for value "search" (type string) at path "_id" for model "Patient"
    at SchemaObjectId.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schema\objectId.js:251:11)
    at SchemaType.applySetters (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1258:12)
    at SchemaType.castForQuery (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1694:17)
    at cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\cast.js:390:32)
    at Query.cast (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:5060:12)
    at Query._castConditions (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2374:10)
    at model.Query._findOne (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2697:8)
    at model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\Admin\Documents\new\server\routes\patients.js:62:21
{
  "stringValue": "\"search\"",
  "kind": "ObjectId",
  "value": "search",
  "path": "_id",
  "reason": {},
  "valueType": "string"
}
2025-08-31 16:49:59 [ERROR]: Registration error: User validation failed: department: `Radiology` is not a valid enum value for path `department`., gender: `male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: department: `Radiology` is not a valid enum value for path `department`., gender: `male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "department": {
      "name": "ValidatorError",
      "message": "`Radiology` is not a valid enum value for path `department`.",
      "properties": {
        "message": "`Radiology` is not a valid enum value for path `department`.",
        "type": "enum",
        "enumValues": [
          "General Medicine",
          "Cardiology",
          "Neurology",
          "Orthopedics",
          "Pediatrics",
          "Gynecology",
          "Dermatology",
          "Ophthalmology",
          "ENT",
          "Psychiatry",
          "Administration",
          "Nursing",
          "Reception"
        ],
        "path": "department",
        "value": "Radiology",
        "length": 9
      },
      "kind": "enum",
      "path": "department",
      "value": "Radiology"
    },
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 16:54:56 [ERROR]: Token verification failed: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`Male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`Male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "male",
          "female",
          "other"
        ],
        "path": "gender",
        "value": "Male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "Male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 16:55:05 [ERROR]: Login error: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`Male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`Male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "male",
          "female",
          "other"
        ],
        "path": "gender",
        "value": "Male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "Male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 16:55:36 [ERROR]: Login error: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`Male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`Male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "male",
          "female",
          "other"
        ],
        "path": "gender",
        "value": "Male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "Male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 16:57:23 [ERROR]: Login error: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`Male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`Male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "male",
          "female",
          "other"
        ],
        "path": "gender",
        "value": "Male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "Male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 16:58:12 [ERROR]: Login error: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `Male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`Male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`Male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "male",
          "female",
          "other"
        ],
        "path": "gender",
        "value": "Male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "Male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 17:03:03 [ERROR]: Registration error: User validation failed: gender: `male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 17:03:28 [ERROR]: Registration error: User validation failed: gender: `male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 17:07:51 [ERROR]: Registration error: User validation failed: gender: `male` is not a valid enum value for path `gender`.
ValidationError: User validation failed: gender: `male` is not a valid enum value for path `gender`.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "gender": {
      "name": "ValidatorError",
      "message": "`male` is not a valid enum value for path `gender`.",
      "properties": {
        "message": "`male` is not a valid enum value for path `gender`.",
        "type": "enum",
        "enumValues": [
          "Male",
          "Female",
          "Other"
        ],
        "path": "gender",
        "value": "male",
        "length": 4
      },
      "kind": "enum",
      "path": "gender",
      "value": "male"
    }
  },
  "_message": "User validation failed"
}
2025-08-31 17:59:30 [ERROR]: Email sending error:
{
  "error": "nodemailer.createTransporter is not a function",
  "recipient": "kelvinalfred56@gmail.com",
  "subject": "Welcome! Please Verify Your Email Address"
}
2025-08-31 17:59:30 [ERROR]: Error sending verification email: nodemailer.createTransporter is not a function
TypeError: nodemailer.createTransporter is not a function
    at sendEmail (C:\Users\Admin\Documents\new\server\utils\sendEmail.js:7:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:98:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-08-31 18:06:24 [ERROR]: Email sending error:
{
  "error": "nodemailer.createTransporter is not a function",
  "recipient": "rachelvedastus@gmail.com",
  "subject": "Welcome! Please Verify Your Email Address"
}
2025-08-31 18:06:24 [ERROR]: Error sending verification email: nodemailer.createTransporter is not a function
TypeError: nodemailer.createTransporter is not a function
    at sendEmail (C:\Users\Admin\Documents\new\server\utils\sendEmail.js:7:36)
    at C:\Users\Admin\Documents\new\server\routes\auth.js:98:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-09-01 00:38:59 [ERROR]: Error starting visit: Visit validation failed: createdBy: Path `createdBy` is required., visitDate: Path `visitDate` is required., doctorId: Path `doctorId` is required., patientId: Path `patientId` is required., visitId: Path `visitId` is required.
ValidationError: Visit validation failed: createdBy: Path `createdBy` is required., visitDate: Path `visitDate` is required., doctorId: Path `doctorId` is required., patientId: Path `patientId` is required., visitId: Path `visitId` is required.
    at Document.invalidate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3358:32)
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\document.js:3119:17
    at C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\schemaType.js:1416:9
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
{
  "errors": {
    "createdBy": {
      "name": "ValidatorError",
      "message": "Path `createdBy` is required.",
      "properties": {
        "message": "Path `createdBy` is required.",
        "type": "required",
        "path": "createdBy"
      },
      "kind": "required",
      "path": "createdBy"
    },
    "visitDate": {
      "name": "ValidatorError",
      "message": "Path `visitDate` is required.",
      "properties": {
        "message": "Path `visitDate` is required.",
        "type": "required",
        "path": "visitDate"
      },
      "kind": "required",
      "path": "visitDate"
    },
    "doctorId": {
      "name": "ValidatorError",
      "message": "Path `doctorId` is required.",
      "properties": {
        "message": "Path `doctorId` is required.",
        "type": "required",
        "path": "doctorId"
      },
      "kind": "required",
      "path": "doctorId"
    },
    "patientId": {
      "name": "ValidatorError",
      "message": "Path `patientId` is required.",
      "properties": {
        "message": "Path `patientId` is required.",
        "type": "required",
        "path": "patientId"
      },
      "kind": "required",
      "path": "patientId"
    },
    "visitId": {
      "name": "ValidatorError",
      "message": "Path `visitId` is required.",
      "properties": {
        "message": "Path `visitId` is required.",
        "type": "required",
        "path": "visitId"
      },
      "kind": "required",
      "path": "visitId"
    }
  },
  "_message": "Visit validation failed"
}
2025-09-01 00:46:33 [ERROR]: Error fetching visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:86:20
{
  "path": "assignedNurse"
}
2025-09-01 00:46:34 [ERROR]: Error fetching active visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:123:20
{
  "path": "assignedNurse"
}
2025-09-01 00:46:34 [ERROR]: Error fetching visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:86:20
{
  "path": "assignedNurse"
}
2025-09-01 00:46:35 [ERROR]: Error fetching active visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:123:20
{
  "path": "assignedNurse"
}
2025-09-01 00:48:54 [ERROR]: Error fetching visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:86:20
{
  "path": "assignedNurse"
}
2025-09-01 00:48:54 [ERROR]: Error fetching active visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:123:20
{
  "path": "assignedNurse"
}
2025-09-01 00:48:55 [ERROR]: Error fetching visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:86:20
{
  "path": "assignedNurse"
}
2025-09-01 00:48:55 [ERROR]: Error fetching active visits: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
StrictPopulateError: Cannot populate path `assignedNurse` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at _populatePath (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4466:21)
    at Function.populate (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\model.js:4433:21)
    at model.Query._find (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:2456:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async model.Query.exec (C:\Users\Admin\Documents\new\server\node_modules\mongoose\lib\query.js:4627:63)
    at async C:\Users\Admin\Documents\new\server\routes\visits.js:123:20
{
  "path": "assignedNurse"
}
{"level":"error","message":"SyntaxError: Unexpected token '\"', \"\"johnson14\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at createStrictSyntaxError (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:169:10)\n    at parse (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:86:15)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)\n    at invokeCallback (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1698:12)","service":"user-service","timestamp":"2025-09-01 03:26:10"}
{"level":"error","message":"Token verification failed: Operation `users.findOne()` buffering timed out after 10000ms","service":"user-service","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:187:23)\n    at listOnTimeout (node:internal/timers:588:17)\n    at process.processTimers (node:internal/timers:523:7)","timestamp":"2025-09-01 14:32:24"}
{"level":"error","message":"Token verification failed: Operation `users.findOne()` buffering timed out after 10000ms","service":"user-service","stack":"MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:187:23)\n    at listOnTimeout (node:internal/timers:588:17)\n    at process.processTimers (node:internal/timers:523:7)","timestamp":"2025-09-01 14:32:32"}
{"level":"error","message":"Error connecting to MongoDB: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017","service":"user-service","timestamp":"2025-09-01 14:32:35"}
{"level":"error","message":"SyntaxError: Unexpected token '\"', \"\"johnson14\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at createStrictSyntaxError (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:169:10)\n    at parse (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:86:15)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)\n    at invokeCallback (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1698:12)","service":"user-service","timestamp":"2025-09-01 14:57:07"}
{"level":"error","message":"SyntaxError: Unexpected token '\"', \"\"johnson14\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at createStrictSyntaxError (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:169:10)\n    at parse (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:86:15)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)\n    at invokeCallback (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1698:12)","service":"user-service","timestamp":"2025-09-01 15:01:10"}
{"level":"error","message":"SyntaxError: Unexpected token '\"', \"\"johnson14\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at createStrictSyntaxError (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:169:10)\n    at parse (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\types\\json.js:86:15)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)\n    at invokeCallback (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1698:12)","service":"user-service","timestamp":"2025-09-01 15:04:21"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:35:57"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:35:57"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:36:13"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:36:13"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:36:24"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:36:24"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:36:42"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:36:42"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:41:35"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:41:35"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:54:54"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:54:54"}
{"level":"error","message":"Token verification failed: user.isLocked is not a function","service":"user-service","stack":"TypeError: user.isLocked is not a function\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:49:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-01 16:55:06"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 16:56:20"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 16:56:21"}
{"kind":"ObjectId","level":"error","message":"Update user error: Cast to ObjectId failed for value \"preferences\" (type string) at path \"_id\" for model \"User\"","path":"_id","reason":{},"service":"user-service","stack":"CastError: Cast to ObjectId failed for value \"preferences\" (type string) at path \"_id\" for model \"User\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/users.js:114:16","stringValue":"\"preferences\"","timestamp":"2025-09-01 16:57:29","value":"preferences","valueType":"string"}
{"kind":"ObjectId","level":"error","message":"Update user error: Cast to ObjectId failed for value \"preferences\" (type string) at path \"_id\" for model \"User\"","path":"_id","reason":{},"service":"user-service","stack":"CastError: Cast to ObjectId failed for value \"preferences\" (type string) at path \"_id\" for model \"User\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/users.js:114:16","stringValue":"\"preferences\"","timestamp":"2025-09-01 16:57:34","value":"preferences","valueType":"string"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 16:58:58"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 16:58:59"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 18:04:15"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 18:04:16"}
{"kind":"ObjectId","level":"error","message":"Update user error: Cast to ObjectId failed for value \"profile\" (type string) at path \"_id\" for model \"User\"","path":"_id","reason":{},"service":"user-service","stack":"CastError: Cast to ObjectId failed for value \"profile\" (type string) at path \"_id\" for model \"User\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/users.js:168:16","stringValue":"\"profile\"","timestamp":"2025-09-01 18:05:15","value":"profile","valueType":"string"}
{"level":"error","message":"ValidationError: Appointment validation failed: duration: Cast to Number failed for value \"1 hour\" (type string) at path \"duration\", createdBy: Path `createdBy` is required., reason: Path `reason` is required., appointmentTime: Path `appointmentTime` is required., appointmentDate: Path `appointmentDate` is required., appointmentId: Path `appointmentId` is required., type: `Follow-up` is not a valid enum value for path `type`., status: `Scheduled` is not a valid enum value for path `status`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at model.$set (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:1480:12)\n    at model.$set (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:1132:16)\n    at model.Document (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:178:12)\n    at model.Model (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:127:12)\n    at new model (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:4834:15)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:2775:20\n    at Array.map (<anonymous>)\n    at Function.create (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:2763:34)\n    at file:///C:/Users/Admin/Documents/new/server/routes/appointments.js:19:43","service":"user-service","timestamp":"2025-09-01 20:45:48"}
{"level":"error","message":"ValidationError: Appointment validation failed: duration: Cast to Number failed for value \"1 hour\" (type string) at path \"duration\", createdBy: Path `createdBy` is required., reason: Path `reason` is required., appointmentTime: Path `appointmentTime` is required., appointmentDate: Path `appointmentDate` is required., appointmentId: Path `appointmentId` is required., status: `Scheduled` is not a valid enum value for path `status`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at model.$set (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:1480:12)\n    at model.$set (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:1132:16)\n    at model.Document (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:178:12)\n    at model.Model (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:127:12)\n    at new model (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:4834:15)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:2775:20\n    at Array.map (<anonymous>)\n    at Function.create (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:2763:34)\n    at file:///C:/Users/Admin/Documents/new/server/routes/appointments.js:19:43","service":"user-service","timestamp":"2025-09-01 20:56:02"}
{"_message":"Appointment validation failed","errors":{"reason":{"kind":"required","message":"Path `reason` is required.","name":"ValidatorError","path":"reason","properties":{"length":0,"message":"Path `reason` is required.","path":"reason","type":"required","value":""},"value":""}},"level":"error","message":"Create appointment error: Appointment validation failed: reason: Path `reason` is required.","service":"user-service","stack":"ValidationError: Appointment validation failed: reason: Path `reason` is required.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-01 20:56:23"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 21:03:31"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"active\" (type string) at path \"_id\" for model \"Visit\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:29:19","service":"user-service","timestamp":"2025-09-01 21:03:32"}
{"level":"error","message":"Get visits error: Cannot populate path `doctor` because it is not in your schema. Set the `strictPopulate` option to false to override.","path":"doctor","service":"user-service","stack":"StrictPopulateError: Cannot populate path `doctor` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:50:12)\n    at _populatePath (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:4466:21)\n    at Function.populate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:4433:21)\n    at model.Query._find (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2456:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:63)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:27:20","timestamp":"2025-09-01 21:17:02"}
{"level":"error","message":"Get visits error: Cannot populate path `doctor` because it is not in your schema. Set the `strictPopulate` option to false to override.","path":"doctor","service":"user-service","stack":"StrictPopulateError: Cannot populate path `doctor` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:50:12)\n    at _populatePath (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:4466:21)\n    at Function.populate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\model.js:4433:21)\n    at model.Query._find (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2456:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:63)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/visits.js:27:20","timestamp":"2025-09-01 21:17:03"}
{"cause":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":3569529,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"errorLabelSet":{},"level":"error","message":"connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":3569529,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"service":"user-service","stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1165:11)\n    at NativeConnection.openUri (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1096:11)\n    at async connectDB (file:///C:/Users/Admin/Documents/new/server/config/database.js:6:18)","timestamp":"2025-09-02 16:58:30"}
{"kind":"ObjectId","level":"error","message":"Update user error: Cast to ObjectId failed for value \"preferences\" (type string) at path \"_id\" for model \"User\"","path":"_id","reason":{},"service":"user-service","stack":"CastError: Cast to ObjectId failed for value \"preferences\" (type string) at path \"_id\" for model \"User\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/users.js:168:16","stringValue":"\"preferences\"","timestamp":"2025-09-03 16:04:06","value":"preferences","valueType":"string"}
{"level":"error","message":"Update preferences error: Cannot read properties of undefined (reading 'id')","service":"user-service","stack":"TypeError: Cannot read properties of undefined (reading 'id')\n    at file:///C:/Users/Admin/Documents/new/server/routes/users.js:119:22\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-09-03 16:08:17"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:44:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:43:35"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:44:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:43:36"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:44:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:44:04"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:44:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:44:05"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:44:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:44:16"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:44:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:44:17"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:45:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:48:40"}
{"level":"error","message":"ReferenceError: logger is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:45:9\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","service":"user-service","timestamp":"2025-09-03 18:48:41"}
{"level":"error","message":"Get doctor queue error: Visit is not defined","service":"user-service","stack":"ReferenceError: Visit is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:39:23\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-03 18:49:33"}
{"level":"error","message":"Get doctor queue error: Visit is not defined","service":"user-service","stack":"ReferenceError: Visit is not defined\n    at file:///C:/Users/Admin/Documents/new/server/routes/doctors.js:39:23\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:88:5\n    at newFn (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at protect (file:///C:/Users/Admin/Documents/new/server/middleware/auth.js:61:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-03 18:49:34"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:22:03"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:22:03"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:23:40"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:23:40"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:24:23"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:24:23"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:42:26"}
{"_message":"Notification validation failed","errors":{"relatedEntity.entityType":{"kind":"enum","message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","name":"ValidatorError","path":"relatedEntity.entityType","properties":{"enumValues":["appointment","patient","visit","labtest","prescription"],"length":7,"message":"`invoice` is not a valid enum value for path `relatedEntity.entityType`.","path":"relatedEntity.entityType","type":"enum","value":"invoice"},"value":"invoice"}},"level":"error","message":"Create invoice error: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.","service":"user-service","stack":"ValidationError: Notification validation failed: relatedEntity.entityType: `invoice` is not a valid enum value for path `relatedEntity.entityType`.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-04 01:42:26"}
{"cause":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":3677552,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"errorLabelSet":{},"level":"error","message":"connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":3677552,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"service":"user-service","stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1165:11)\n    at NativeConnection.openUri (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1096:11)\n    at async connectDB (file:///C:/Users/Admin/Documents/new/server/config/database.js:6:18)","timestamp":"2025-09-04 18:43:46"}
{"_message":"Appointment validation failed","errors":{"reason":{"kind":"required","message":"Path `reason` is required.","name":"ValidatorError","path":"reason","properties":{"length":0,"message":"Path `reason` is required.","path":"reason","type":"required","value":""},"value":""}},"level":"error","message":"Create appointment error: Appointment validation failed: reason: Path `reason` is required.","service":"user-service","stack":"ValidationError: Appointment validation failed: reason: Path `reason` is required.\n    at Document.invalidate (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\document.js:3119:17\n    at C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1416:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-09-06 23:10:54"}
{"code":5107201,"codeName":"Location5107201","errorLabelSet":{},"errorResponse":{"code":5107201,"codeName":"Location5107201","errmsg":"invalid argument to $limit stage: Expected an integer, but found NaN in: $limit: nan.0","ok":0},"level":"error","message":"Get invoices error: invalid argument to $limit stage: Expected an integer, but found NaN in: $limit: nan.0","ok":0,"service":"user-service","stack":"MongoServerError: invalid argument to $limit stage: Expected an integer, but found NaN in: $limit: nan.0\n    at Connection.sendCommand (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cmap\\connection.js:305:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cmap\\connection.js:333:26)\n    at async Server.command (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\sdam\\server.js:171:29)\n    at async AggregateOperation.executeCommand (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\command.js:76:16)\n    at async AggregateOperation.execute (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\aggregate.js:86:16)\n    at async tryOperation (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:207:20)\n    at async executeOperation (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:75:16)\n    at async AggregationCursor._initialize (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cursor\\aggregation_cursor.js:56:26)\n    at async AggregationCursor.cursorInit (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:632:27)","timestamp":"2025-09-07 23:01:32"}
{"code":5107201,"codeName":"Location5107201","errorLabelSet":{},"errorResponse":{"code":5107201,"codeName":"Location5107201","errmsg":"invalid argument to $limit stage: Expected an integer, but found NaN in: $limit: nan.0","ok":0},"level":"error","message":"Get invoices error: invalid argument to $limit stage: Expected an integer, but found NaN in: $limit: nan.0","ok":0,"service":"user-service","stack":"MongoServerError: invalid argument to $limit stage: Expected an integer, but found NaN in: $limit: nan.0\n    at Connection.sendCommand (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cmap\\connection.js:305:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cmap\\connection.js:333:26)\n    at async Server.command (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\sdam\\server.js:171:29)\n    at async AggregateOperation.executeCommand (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\command.js:76:16)\n    at async AggregateOperation.execute (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\aggregate.js:86:16)\n    at async tryOperation (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:207:20)\n    at async executeOperation (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:75:16)\n    at async AggregationCursor._initialize (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cursor\\aggregation_cursor.js:56:26)\n    at async AggregationCursor.cursorInit (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:632:27)","timestamp":"2025-09-07 23:03:47"}
{"level":"error","message":"Delete appointment error: appointment.remove is not a function","service":"user-service","stack":"TypeError: appointment.remove is not a function\n    at file:///C:/Users/Admin/Documents/new/server/routes/appointments.js:148:23\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-07 23:30:04"}
{"kind":"ObjectId","level":"error","message":"Update user error: Cast to ObjectId failed for value \"change-password\" (type string) at path \"_id\" for model \"User\"","path":"_id","reason":{},"service":"user-service","stack":"CastError: Cast to ObjectId failed for value \"change-password\" (type string) at path \"_id\" for model \"User\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/users.js:190:16","stringValue":"\"change-password\"","timestamp":"2025-09-08 20:17:58","value":"change-password","valueType":"string"}
{"kind":"ObjectId","level":"error","message":"Update user error: Cast to ObjectId failed for value \"profile\" (type string) at path \"_id\" for model \"User\"","path":"_id","reason":{},"service":"user-service","stack":"CastError: Cast to ObjectId failed for value \"profile\" (type string) at path \"_id\" for model \"User\"\n    at SchemaObjectId.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async file:///C:/Users/Admin/Documents/new/server/routes/users.js:190:16","stringValue":"\"profile\"","timestamp":"2025-09-08 20:37:11","value":"profile","valueType":"string"}
{"cause":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":121568943,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"errorLabelSet":{},"level":"error","message":"Server selection timed out after 5000 ms","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":121568943,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"service":"user-service","stack":"MongooseServerSelectionError: Server selection timed out after 5000 ms\n    at _handleConnectionErrors (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1165:11)\n    at NativeConnection.openUri (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1096:11)\n    at async connectDB (file:///C:/Users/Admin/Documents/new/server/config/database.js:6:18)","timestamp":"2025-09-16 01:50:55"}
{"cause":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":121866696,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"errorLabelSet":{},"level":"error","message":"Server selection timed out after 5000 ms","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"localhost:27017":{"$clusterTime":null,"address":"localhost:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":121866696,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"service":"user-service","stack":"MongooseServerSelectionError: Server selection timed out after 5000 ms\n    at _handleConnectionErrors (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1165:11)\n    at NativeConnection.openUri (C:\\Users\\Admin\\Documents\\new\\server\\node_modules\\mongoose\\lib\\connection.js:1096:11)\n    at async connectDB (file:///C:/Users/Admin/Documents/new/server/config/database.js:6:18)","timestamp":"2025-09-16 01:55:53"}
{"level":"error","message":"Delete appointment error: appointment.remove is not a function","service":"user-service","stack":"TypeError: appointment.remove is not a function\n    at file:///C:/Users/Admin/Documents/new/server/routes/appointments.js:151:23\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-17 01:53:44"}
